### ISSUE TITLE
typescript and jasmine versions are causing an error

### ISSUE THREAD

**Issue by paszin** [projectSHAI/GOATstack#2]
When running `npm start` I get
```
ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:52 
    '=' expected.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:38 
    A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:46 
    Cannot find name 'keyof'.
```
According to http://stackoverflow.com/a/42190918 it is a problem with typescript and jasmine.
package.json: 
```

"typescript": "2.0.10",
"@types/jasmine": "^2.5.41",

```

I updated typescript to 2.1.6 which solved the problem for me.

**Comment by JCThomas4214** [comment]
Hey @paszin 

We're currently updating the generator to use Yarn instead of standard npm as this error is due to @types/jasmine package version as you stated above.

If you update typescript to 2.1.6 you might run into problems with the production environment build.

Instead stick with 2.0.10 for now, delete your modules folder, and do a "[yarn](https://yarnpkg.com/en/) install" and that should fix the issue

Also, Thank you for the typescript/jasmine comparability update!

**Comment by paszin** [comment]
As mentioned in #3, same result.
