### ISSUE TITLE
Livereload not working on Ubuntu 16

### ISSUE THREAD

**Issue by paszin** [projectSHAI/GOATstack#3]
Hi, 

I experimenting with the goat stack template. Thanks for making this generator. But I realized that livereload is not working. 
`npm start` output is `[...] Webpack is watching the files… [...]`and I can also find the variable livereload which is set to true in `config/env/development.ts`. But unfortunately it is not working.
Can anyone reproduce this issue?

**Comment by JCThomas4214** [comment]
Webpack's DevServer's hot modules plugin might be encountering some issues because of the package version consistencies. Remove your node_modules folder and try a "[yarn](https://yarnpkg.com/en/) install" instead.

**Comment by JCThomas4214** [comment]
Forgort to mention, any livereload variables in the config/env/** are disconnected and can be deleted. All dev environment reloading will be done with the hot modules middleware in [Webpack DevServer](https://github.com/webpack/webpack-dev-server)

We apologize for the inconvenience :)

**Comment by paszin** [comment]
> Webpack's DevServer's hot modules plugin might be encountering some issues because of the package version consistencies. Remove your node_modules folder and try a "yarn install" instead.

Thanks for your answer, but unfortunately it doesn't solve the issue. 
It's getting worse: 
```
webpack: bundle is now VALID.
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/paszin/Documents/goattest1/dist/**/*
[nodemon] starting `node dist`
[nodemon] Internal watch failed: watch /home/paszin/Documents/goattest1/dist ENOSPC

/home/paszin/Documents/goattest1/node_modules/webpack-shell-plugin/lib/index.js:168
        throw error;
        ^

```

I am using Ubuntu 16. Any ideas how to debug this?

**Comment by projectSHAI** [comment]
Hey Paszin, thanks for using our project we hope you like it! 

I have an Ubuntu 16 environment, I'm going to try to recreate your issues.

I'll edit this post once I find some conclusive results. Stay tuned!

Edit: Good news, I was able to reproduce your error, I'm working on a solution now.

Edit 2: Alright, I found a solution to our problem. Which is an environment problem in relation to nodemon, and Ubuntu.

Solution:
I recommend increasing the number of files a single ubuntu user is allowed to watch by executing the below commands in your terminal

1) `echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
2) `yarn start`

Reason this issue is occurring on Ubuntu 16:

`ENOSPC` is an error that means: Error No more hard-disk space available. Do not fear, this does not mean that nodemon and livereload are flooding your storage, Ubuntu 16 just sets a limit in the system for how many files a single user can watch. Which in this case is being maxed out. So the above command line increases that limit to 582,222 files per user.

The reason the maximum is being reached is because we also have livereload watching the node_modules directory. If you want you could also create a nodemon.json file and ignore the node_modules folder. However, I would recommend using my solution instead, because any changed in node_modules will require re compiling your project.

[Stack overflow solution reference](http://stackoverflow.com/questions/34662574/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc)
[Example nodemon.json configuration](https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md)

**Comment by paszin** [comment]
Thank you for the fast and detailed response! This solved the problem for me.
